apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - github.com/argoproj/argo-cd//manifests/cluster-install?ref=stable
  - namespace.yaml
  - application.yaml
  - ingress.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --insecure
